apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: [NAMESPACE]-ingress
  namespace: NAMESPACE
spec:
  tls:
  - hosts:
    - [NAMESPACE].[ENVIROMENT].[FQDN]
    secretName: [NAMESPACE]-secret
  rules:
  - host: [NAMESPACE].[ENVIROMENT].[FQDN]
    http:
      paths:
      - path: /INSTANCE
        backend:
          serviceName: [INSTANCE]-svc
          servicePort: 80
          
