apiVersion: v1
kind: Secret
metadata:
  name: registry-minikube
  namespace: nuevo-test
data:
  .dockerconfigjson: ewogICAgICAgICJhdXRocyI6IHsKICAgICAgICAgICAgICAgICJyZWdpc3RyeS5lbnRvcm5vMS5vcmc6MzI2ODgiOiB7CiAgICAgICAgICAgICAgICAgICAgICAgICJhdXRoIjogImNtVm5hWE4wY25rdGRYTmxjanBKYzI5MGNtOXNMakl3TVRnPSIKICAgICAgICAgICAgICAgIH0KICAgICAgICB9LAogICAgICAgICJIdHRwSGVhZGVycyI6IHsKICAgICAgICAgICAgICAgICJVc2VyLUFnZW50IjogIkRvY2tlci1DbGllbnQvMTguMDYuMS1jZSAobGludXgpIgogICAgICAgIH0KfQo=
type: kubernetes.io/dockerconfigjson
