# Generated by Django 2.1.3 on 2018-11-21 17:50

import datetime
from django.conf import settings
import django.core.files.storage
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AfAuditoria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aud_entidad_id', models.IntegerField()),
                ('aud_entidad_tipo', models.CharField(max_length=100)),
                ('aud_detalle_pre', models.CharField(blank=True, max_length=250, null=True)),
                ('aud_detalle_pos', models.CharField(blank=True, max_length=250, null=True)),
                ('usu_username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='afauditorias', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'managed': True,
                'db_table': 'af_auditoria',
            },
        ),
        migrations.CreateModel(
            name='AfCiclo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cic_fecha_inicio', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('cic_fecha_fin', models.DateTimeField(blank=True, null=True)),
                ('num_replicas', models.IntegerField(default=1, verbose_name='Réplicas')),
                ('tarifa', models.FloatField(blank=True, null=True)),
            ],
            options={
                'managed': True,
                'db_tablespace': 'af_instancia',
                'db_table': 'af_ciclo',
            },
        ),
        migrations.CreateModel(
            name='AfEntorno',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ent_nombre', models.CharField(max_length=100, unique=True, verbose_name='Nombre del entorno')),
                ('ent_descripcion', models.CharField(blank=True, max_length=250, null=True, verbose_name='Descripción del entorno')),
                ('ent_activo', models.BooleanField(default=1, verbose_name='Activo')),
                ('ent_config_file', models.FileField(blank=True, storage=django.core.files.storage.FileSystemStorage(location='/var/www/afcloud/'), upload_to='', verbose_name='Fichero de entorno')),
                ('ent_json_file', models.FileField(blank=True, storage=django.core.files.storage.FileSystemStorage(location='/var/www/afcloud/'), upload_to='', verbose_name='Json')),
                ('registry_hash', models.CharField(blank=True, max_length=1000)),
                ('nfs_server', models.GenericIPAddressField(blank=True, null=True)),
                ('ent_deleted', models.BooleanField(default=0, verbose_name='Eliminado')),
            ],
            options={
                'managed': True,
                'db_table': 'af_entorno',
            },
        ),
        migrations.CreateModel(
            name='AfEstadosIncidencia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(blank=True, max_length=100, null=True)),
                ('descripcion', models.CharField(blank=True, max_length=250, null=True)),
            ],
            options={
                'managed': True,
                'db_table': 'af_estado_incidencia',
            },
        ),
        migrations.CreateModel(
            name='AfGlobalconf',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fqdn', models.CharField(max_length=100, verbose_name='FQDN')),
                ('crt_file', models.FileField(blank=True, upload_to='cert/', verbose_name='Fichero crt')),
                ('key_file', models.FileField(blank=True, upload_to='key/', verbose_name='Fichero key')),
                ('is_done', models.BooleanField(default=0, verbose_name='Configuracion realizada')),
                ('email', models.EmailField(blank=True, max_length=100)),
            ],
            options={
                'managed': True,
                'db_table': 'af_globalconf',
            },
        ),
        migrations.CreateModel(
            name='AfIncidencia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asunto', models.CharField(blank=True, max_length=250, null=True, verbose_name='Asunto')),
                ('cuerpo', models.CharField(blank=True, max_length=1000, null=True, verbose_name='Cuerpo')),
                ('fecha_apertura', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de apertura')),
                ('fecha_updated', models.DateTimeField(auto_now=True, verbose_name='Actualizada')),
                ('fecha_cierre', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de cierre')),
                ('estado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='portal.AfEstadosIncidencia')),
            ],
            options={
                'managed': True,
                'db_tablespace': 'af_usuario',
                'db_table': 'af_incidencia',
            },
        ),
        migrations.CreateModel(
            name='AfInstancia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ins_kubeid', models.CharField(max_length=100)),
                ('ins_uri', models.CharField(blank=True, max_length=100, null=True)),
                ('ins_activo', models.BooleanField(default=1, verbose_name='Activo')),
                ('ins_unique_name', models.CharField(blank=True, max_length=100, verbose_name='Nombre del Despliegue')),
            ],
            options={
                'managed': True,
                'db_tablespace': 'af_linea_catalogo',
                'db_table': 'af_instancia',
            },
        ),
        migrations.CreateModel(
            name='AfLineaCatalogo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lca_tarifa', models.FloatField(blank=True, null=True)),
                ('lca_activo', models.BooleanField(default=1, verbose_name='Activo')),
            ],
            options={
                'managed': True,
                'db_tablespace': ('af_servicio', 'af_proyecto'),
                'db_table': 'af_linea_catalogo',
            },
        ),
        migrations.CreateModel(
            name='AfMailServer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_server', models.CharField(max_length=100, verbose_name='Servidor de correo')),
                ('port', models.IntegerField(verbose_name='Puerto')),
                ('usuario', models.CharField(max_length=100, verbose_name='Usuario')),
                ('passwd', models.CharField(max_length=100, verbose_name='Contraseña')),
                ('tls', models.BooleanField(default=1, verbose_name='Usa TLS')),
            ],
            options={
                'managed': True,
                'db_table': 'af_mail_server',
            },
        ),
        migrations.CreateModel(
            name='AfNotasIncidencia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Fecha de creación')),
                ('asunto', models.CharField(blank=True, max_length=50, null=True)),
                ('notas', models.CharField(blank=True, max_length=1000, null=True, verbose_name='Notas asociadas')),
            ],
            options={
                'managed': True,
                'db_tablespace': 'af_incidencia',
                'db_table': 'af_notas_incidencias',
            },
        ),
        migrations.CreateModel(
            name='AfNotify_Tipo_instancia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('catalogo', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='portal.AfLineaCatalogo')),
                ('despliegue', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='portal.AfInstancia')),
                ('incidencia', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='portal.AfIncidencia')),
            ],
            options={
                'managed': True,
                'db_table': 'af_notify_tipo_instancia',
            },
        ),
        migrations.CreateModel(
            name='AfPerfil',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('per_activo', models.BooleanField(default=1, verbose_name='Activo')),
            ],
            options={
                'managed': True,
                'db_tablespace': ('af_usuario', 'af_proyecto', 'af_tipo_perfil'),
                'db_table': 'af_perfil',
            },
        ),
        migrations.CreateModel(
            name='AfProyecto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pro_nombre', models.CharField(max_length=100, unique=True, verbose_name='Nombre')),
                ('pro_nombre_k8s', models.CharField(blank=True, max_length=100, null=True, verbose_name='Nombre k8s')),
                ('pro_descripcion', models.CharField(blank=True, max_length=250, null=True, verbose_name='Descripción')),
                ('pro_activo', models.BooleanField(default=1, verbose_name='Activo')),
            ],
            options={
                'managed': True,
                'db_table': 'af_proyecto',
            },
        ),
        migrations.CreateModel(
            name='AfRelEntPro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rep_activo', models.BooleanField(default=1, verbose_name='Activo')),
                ('ent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portal.AfEntorno')),
                ('pro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portal.AfProyecto')),
            ],
            options={
                'managed': True,
                'db_tablespace': ('af_entorno', 'af_proyecto'),
                'db_table': 'af_rel_ent_pro',
            },
        ),
        migrations.CreateModel(
            name='AfServicio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ser_nombre', models.CharField(max_length=100, verbose_name='Nombre del servicio')),
                ('ser_descripcion', models.CharField(blank=True, max_length=250, null=True, verbose_name='Descripción')),
                ('ser_tarifa', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Tarifa')),
                ('ser_activo', models.BooleanField(default=1, verbose_name='Activo')),
                ('ser_yaml_file', models.FileField(blank=True, storage=django.core.files.storage.FileSystemStorage(location='/var/www/afcloud/'), upload_to='', verbose_name='Deployment yaml')),
                ('ser_min_replicas', models.IntegerField(default=1, verbose_name='Min replicas')),
                ('ser_max_replicas', models.IntegerField(default=1, verbose_name='Min replicas')),
                ('ser_deleted', models.BooleanField(default=0, verbose_name='Eliminado')),
            ],
            options={
                'managed': True,
                'db_table': 'af_servicio',
            },
        ),
        migrations.CreateModel(
            name='AfTipoNotify',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desc', models.CharField(max_length=100, verbose_name='Tipo de notificación')),
                ('short_desc', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'managed': True,
                'db_table': 'af_tipo_notificacion',
            },
        ),
        migrations.CreateModel(
            name='AfTipoPerfil',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tpe_nombre', models.CharField(max_length=100)),
                ('tpe_descripcion', models.CharField(blank=True, max_length=250, null=True)),
            ],
            options={
                'managed': True,
                'db_table': 'af_tipo_perfil',
            },
        ),
        migrations.CreateModel(
            name='AfUserNotify',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Fecha de creación')),
                ('readed', models.BooleanField(default=0, verbose_name='Leida')),
            ],
            options={
                'managed': True,
                'db_table': 'af_user_notify',
            },
        ),
        migrations.CreateModel(
            name='AfUsuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usu_administrador', models.BooleanField(default=False, verbose_name='Usuario administrador afcloud')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'managed': True,
                'db_table': 'af_usuario',
            },
        ),
        migrations.AddField(
            model_name='afusernotify',
            name='from_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='portal.AfUsuario'),
        ),
        migrations.AddField(
            model_name='afusernotify',
            name='to_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='portal.AfUsuario'),
        ),
        migrations.AddField(
            model_name='afperfil',
            name='pro',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portal.AfProyecto'),
        ),
        migrations.AddField(
            model_name='afperfil',
            name='tpe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portal.AfTipoPerfil'),
        ),
        migrations.AddField(
            model_name='afperfil',
            name='usu',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portal.AfUsuario'),
        ),
        migrations.AddField(
            model_name='afnotify_tipo_instancia',
            name='integrante',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='portal.AfPerfil'),
        ),
        migrations.AddField(
            model_name='afnotify_tipo_instancia',
            name='notify',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='portal.AfUserNotify'),
        ),
        migrations.AddField(
            model_name='afnotify_tipo_instancia',
            name='tipo',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='portal.AfTipoNotify'),
        ),
        migrations.AddField(
            model_name='afnotasincidencia',
            name='autor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='portal.AfUsuario'),
        ),
        migrations.AddField(
            model_name='afnotasincidencia',
            name='incidencia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='portal.AfIncidencia'),
        ),
        migrations.AddField(
            model_name='aflineacatalogo',
            name='pro',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portal.AfProyecto'),
        ),
        migrations.AddField(
            model_name='aflineacatalogo',
            name='ser',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='portal.AfServicio'),
        ),
        migrations.AddField(
            model_name='afinstancia',
            name='lca',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portal.AfLineaCatalogo'),
        ),
        migrations.AddField(
            model_name='afinstancia',
            name='rep',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portal.AfRelEntPro'),
        ),
        migrations.AddField(
            model_name='afincidencia',
            name='usu',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='portal.AfUsuario'),
        ),
        migrations.AddField(
            model_name='afciclo',
            name='ins',
            field=models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='afciclos', to='portal.AfInstancia'),
        ),
    ]
