# Generated by Django 2.1.1 on 2018-11-12 08:06

import datetime
from django.conf import settings
import django.core.files.storage
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AfAuditoria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aud_entidad_id', models.IntegerField()),
                ('aud_entidad_tipo', models.CharField(max_length=100)),
                ('aud_detalle_pre', models.CharField(blank=True, max_length=250, null=True)),
                ('aud_detalle_pos', models.CharField(blank=True, max_length=250, null=True)),
                ('usu_username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='afauditorias', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'af_auditoria',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='AfCiclo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cic_fecha_inicio', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('cic_fecha_fin', models.DateTimeField(blank=True, default=datetime.datetime.now)),
            ],
            options={
                'db_tablespace': 'af_instancia',
                'db_table': 'af_ciclo',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='AfEntorno',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ent_nombre', models.CharField(max_length=100, unique=True, verbose_name='Nombre del entorno')),
                ('ent_descripcion', models.CharField(blank=True, max_length=250, null=True, verbose_name='Descripción del entorno')),
                ('ent_activo', models.BooleanField(default=1, verbose_name='Activo')),
                ('ent_config_file', models.FileField(blank=True, storage=django.core.files.storage.FileSystemStorage(location='/var/www/afcloud/'), upload_to='', verbose_name='Fichero de entorno')),
                ('ent_json_file', models.FileField(blank=True, storage=django.core.files.storage.FileSystemStorage(location='/var/www/afcloud/'), upload_to='', verbose_name='Json')),
                ('registry_hash', models.CharField(blank=True, max_length=1000)),
                ('nfs_server', models.GenericIPAddressField(blank=True, null=True)),
            ],
            options={
                'db_table': 'af_entorno',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='AfGlobalconf',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fqdn', models.CharField(max_length=100, verbose_name='FQDN')),
                ('crt_file', models.FileField(blank=True, upload_to='cert/', verbose_name='Fichero crt')),
                ('key_file', models.FileField(blank=True, upload_to='key/', verbose_name='Fichero key')),
                ('is_done', models.BooleanField(default=0, verbose_name='Configuracion realizada')),
            ],
            options={
                'db_table': 'af_globalconf',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='AfInstancia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ins_kubeid', models.CharField(max_length=100)),
                ('ins_uri', models.CharField(blank=True, max_length=100, null=True)),
                ('ins_activo', models.BooleanField(default=1, verbose_name='Activo')),
                ('ins_unique_name', models.CharField(blank=True, max_length=100, verbose_name='Nombre del Despliegue')),
            ],
            options={
                'db_tablespace': 'af_linea_catalogo',
                'db_table': 'af_instancia',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='AfLineaCatalogo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lca_tarifa', models.FloatField(blank=True, null=True)),
                ('lca_activo', models.BooleanField(default=1, verbose_name='Activo')),
            ],
            options={
                'db_tablespace': ('af_servicio', 'af_proyecto'),
                'db_table': 'af_linea_catalogo',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='AfPerfil',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('per_activo', models.BooleanField(default=1, verbose_name='Activo')),
            ],
            options={
                'db_tablespace': ('af_usuario', 'af_proyecto', 'af_tipo_perfil'),
                'db_table': 'af_perfil',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='AfProyecto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pro_nombre', models.CharField(max_length=100, unique=True, verbose_name='Nombre')),
                ('pro_nombre_k8s', models.CharField(blank=True, max_length=100, null=True, verbose_name='Nombre k8s')),
                ('pro_descripcion', models.CharField(blank=True, max_length=250, null=True, verbose_name='Descripción')),
                ('pro_activo', models.BooleanField(default=1, verbose_name='Activo')),
            ],
            options={
                'db_table': 'af_proyecto',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='AfRelEntPro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rep_activo', models.BooleanField(default=1, verbose_name='Activo')),
                ('ent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portal.AfEntorno')),
                ('pro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portal.AfProyecto')),
            ],
            options={
                'db_tablespace': ('af_entorno', 'af_proyecto'),
                'db_table': 'af_rel_ent_pro',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='AfServicio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ser_nombre', models.CharField(max_length=100, verbose_name='Nombre del servicio')),
                ('ser_descripcion', models.CharField(blank=True, max_length=250, null=True, verbose_name='Descripción')),
                ('ser_tarifa', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Tarifa')),
                ('ser_activo', models.BooleanField(default=1, verbose_name='Activo')),
                ('ser_yaml_file', models.FileField(blank=True, storage=django.core.files.storage.FileSystemStorage(location='/var/www/afcloud/'), upload_to='', verbose_name='Deployment yaml')),
                ('ser_min_replicas', models.IntegerField(default=1, verbose_name='Min replicas')),
                ('ser_max_replicas', models.IntegerField(default=1, verbose_name='Min replicas')),
                ('ser_deleted', models.BooleanField(default=0, verbose_name='Eliminado')),
            ],
            options={
                'db_table': 'af_servicio',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='AfTipoPerfil',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tpe_nombre', models.CharField(max_length=100)),
                ('tpe_descripcion', models.CharField(blank=True, max_length=250, null=True)),
            ],
            options={
                'db_table': 'af_tipo_perfil',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='AfUsuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usu_administrador', models.BooleanField(default=False, verbose_name='Usuario administrador afcloud')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'af_usuario',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='afperfil',
            name='pro',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portal.AfProyecto'),
        ),
        migrations.AddField(
            model_name='afperfil',
            name='tpe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portal.AfTipoPerfil'),
        ),
        migrations.AddField(
            model_name='afperfil',
            name='usu',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portal.AfUsuario'),
        ),
        migrations.AddField(
            model_name='aflineacatalogo',
            name='pro',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portal.AfProyecto'),
        ),
        migrations.AddField(
            model_name='aflineacatalogo',
            name='ser',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='portal.AfServicio'),
        ),
        migrations.AddField(
            model_name='afinstancia',
            name='lca',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portal.AfLineaCatalogo'),
        ),
        migrations.AddField(
            model_name='afinstancia',
            name='rep',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portal.AfRelEntPro'),
        ),
        migrations.AddField(
            model_name='afciclo',
            name='ins',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='afciclos', to='portal.AfInstancia'),
        ),
    ]
