# Generated by Django 2.1.1 on 2018-10-13 05:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='afauditoria',
            name='usu_username',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='afauditorias', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='afciclo',
            name='ins',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='afciclos', to='portal.AfInstancia'),
        ),
    ]
