# Generated by Django 2.1.1 on 2018-10-18 10:35

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0003_auto_20181016_0822'),
    ]

    operations = [
        migrations.AddField(
            model_name='afservicio',
            name='ser_max_replicas',
            field=models.IntegerField(default=1, verbose_name='Min replicas'),
        ),
        migrations.AddField(
            model_name='afservicio',
            name='ser_min_replicas',
            field=models.IntegerField(default=1, verbose_name='Min replicas'),
        ),
        migrations.AddField(
            model_name='afservicio',
            name='ser_yaml_file',
            field=models.FileField(blank=True, storage=django.core.files.storage.FileSystemStorage(location='/var/www/media/'), upload_to='', verbose_name='Deployment yaml'),
        ),
    ]
